refactor some lines and permissions
coronatorid/contooling pull request #1
Opened 2020-12-28 23:47 UTC by januridp

2020-12-29 02:14 UTC, insomnius commented
Nice contribution @januridp . Overall good, namun ada kebutuhkan untuk membuat server username dan serverhost menjadi dynamic, bisa disupport di PR ini juga kah?

2020-12-29 15:01 UTC, januridp commented
oh berarti yang pertama bener gitu ya? itu udah di balikin ke awal, benarkah seperti itu pak @insomnius ?

2020-12-29 18:36 UTC, insomnius requested changes

2020-12-29 18:36 UTC, insomnius commented on general/deploy.sh
> +    mkdir -p ~/.ssh && chmod 700 ~/.ssh && cd ~/.ssh/
Ini setelah `cd` ke `~/.ssh` gak dibalikin lagi kah ke directory sebelumnya? Karena workdir dari code-code dibawah itu harusnya di `./$SERVICE`.

Bisa pake `cd -` harusnya sih.

2020-12-29 22:39 UTC, insomnius commented
Nice @januridp . Gue coba dulu test di local ya.

2020-12-30 12:34 UTC, insomnius commented
Btw pull master dulu dong @januridp

2020-12-30 22:50 UTC, insomnius requested changes

2020-12-30 22:50 UTC, insomnius commented on general/deploy.sh
> +    cat ./general/ssh-config-file > ~/.ssh/config && chmod 644 ~/.ssh/config
Oh ya, satu lagi. Bikin jadi gini dong.

```suggestion
    cat ./general/ssh-config-file >> ~/.ssh/config && chmod 644 ~/.ssh/config
```

Lebih safe append line daripada overwrite deh kayanya, takut ada unexpected behaviour juga di github action nya

2020-12-30 22:51 UTC, insomnius reviewed
Tambahan

2020-12-30 22:51 UTC, insomnius commented on general/deploy.sh
> +    echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa && echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
Untuk yang ini kayanya malah lebih bagus dibikin untuk overwrite.

```suggestion
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
```

Kalo ke append gini nanti keynya malah jadi gak valid kalau jalan 2 kali

2020-12-31 09:42 UTC, insomnius commented
Sip sip, gue coba lagi di local ya.

2020-12-31 20:04 UTC, merged